### ISSUE TITLE
Change `Send_Cube_State.py` into a Python `module` for testing

### ISSUE THREAD

**Issue by WK-GiHu** [TheOneDarkEye/Cube-Solver#2]
@TheOneDarkEye 

Insert the following at this line, update the code in `Send_Cube_State.py` so i can review it.
https://github.com/TheOneDarkEye/Cube-Solver/blob/ceb2ca80ba952415998d3443a6fcb58eb910a842/Send_Cube_State.py#L597

```
if __name__ == '__main__':
    # ALL following lines habe to be indented

```

Add a **new file** called `cube_testing.py`
Copy the following into it and runn it from a console window, like `python cube_testing.py`
We have to see the error messages, therefore neede to run in a console window!

```
import Send_Cube_State as scs

if __name__ == '__main__':
    scs.enter_yellow_face()


```

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
Done

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

You didn't fullfill the comment `# ALL follwing lines...`, please indent

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
Is that right now?

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

Seems OK, but allways indent the comment linese `# ....` also.
It's more readable.
See my update **first** comment at the top and create a new file

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
"runn it from a console window, like python cube_testing.py
We have to see the error messages, therefore neede to run in a console window!"
I don't understand this. I've copied the code into the new file. Do i run it from github? what's python cube_testing.py?

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 
>Do i run it from github?
No, you can't run anything at GitHub, also not online becaus `tkinter` is a **GUI** which needs a local window manager. On MACOS this is what you see as **Desktop** and **Icons**.
I'm not sure if it's realy called `console window` at MACOS.

Do you have something like a `System Menu` you can select?
I have to search for a online reference for this so i can point to the right direction, this needs some time, please be patient...

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
I ran the code in the 'Atom' application and this was the error message...

Traceback (most recent call last):
  File "<string>", line 4, in <module>
ImportError: No module named Send_Cube_State.py
[Finished in 0.095s]

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
i'm sorry if i sound impatient. i don't know much about coding and i greatly appreciate your help.

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 
> I ran the code in the 'Atom' application and this was the error message...
Ok, running from `Atom` which shows the error messages will do it for now.

> ImportError: No module named Send_Cube_State.py

For testing, you need the file `Send_Cube_State.py` also in the same folder where you copied `cube_testing.py`. Try again

**Comment by TheOneDarkEye** [comment]
Yeah, that worked. There was no error. The window popped up for the yellow face and it was the same result.

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 
>Yeah, that worked. There was no error.

Next Step we add a trace to see the value of the variable `counter[x]`

Add before this line
https://github.com/TheOneDarkEye/Cube-Solver/blob/d944c13ddb3e65d439b53fc96eef3f6ea87f5998/Send_Cube_State.py#L132

`print('counter[x]={}'.format(counter[x]))
`

### You have to do this on GitHub so i can review it and also in your local file
### Best approach, edit GitHub and copy the whole file to you local folder

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
Done. Each time i click the buttons the value of "counter[x]" increases. So if i clicked it once it would equal 0 if i click again it equals 1 and so on until after 5 when i loops back to 0, and then 1 and 2 etc...

**Comment by TheOneDarkEye** [comment]
![Screen Shot 2019-09-06 at 6 15 46 pm](https://user-images.githubusercontent.com/40260331/64412277-605e1980-d0d2-11e9-8bd8-7c53e74d6666.png)

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 
>Each time i click the buttons the value of "counter[x]" increases.

But you tell, the color didn't change?

**Comment by TheOneDarkEye** [comment]
@WK-GiHu
no it didn't

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

Add the following, beneath the line `print('counter....`

```
        config = bb[x].ss.config()
        print('bb:{}'.format(config['background']))

```

**Comment by TheOneDarkEye** [comment]
@WK-GiHu
Done. Each line was the result of one click, but there was no color change
![Screen Shot 2019-09-06 at 6 43 34 pm](https://user-images.githubusercontent.com/40260331/64414233-5dfdbe80-d0d6-11e9-8f07-f7ee36633528.png)

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
GTG, thanks for the help so far. I'm signing out for now. I'll get in touch sometime in the next week...

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

Last result , the colors are changing in the `Button` object.
I feel my first guess, `Mojave` and `2.7` seems matching.
Next we try to color a `Canvas` object.
