### ISSUE TITLE
Testing `Canvas` blue and `Button` red

### ISSUE THREAD

**Issue by WK-GiHu** [TheOneDarkEye/Cube-Solver#3]
@TheOneDarkEye 

This is independant from `Cube-Solver`, to verify your `OS` and `Python Tkinter` are able to show `background=` colors.

Create a new file `CanvasBlueButtonRed.py` and insert the following:

```
import Tkinter as tk

class App(tk.Tk):
    COLORS = ('white', 'green', 'yellow')
    def __init__(self):
        tk.Tk.__init__(self)
        self.color = -1
        
        self.canvas = canvas = tk.Canvas(self, width=100, height=100, background='blue')
        canvas.pack()
        
        self.button = button = tk.Button(self, text='RED', background='red', command=self.next)
        button.pack()
        
    def next(self):
        self.color += 1
        if self.color >= len(App.COLORS): self.color = 0
        color = App.COLORS[self.color]
        
        self.canvas.configure(background=color)
        self.button.configure(background=color, activebackground=color)

if __name__ == '__main__':
    App().mainloop()

```
The result:
![grafik](https://user-images.githubusercontent.com/22146250/64418187-d34b9e00-d09a-11e9-8256-f3e7583c277d.png)

**Comment by TheOneDarkEye** [comment]
@WK-GiHu
the button labelled red is not red (it's white)

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

>the button labelled red is not red (it's white)

As i thought, Buttons are bound to the Color Theme of the MACOS Desktop.
Are the `Canvas` colored `blue` at startup and did the colors change on click?
if Yes, you have to use `Canvas` instead of `Button`.

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
Yes, the canvas was blue at startup and changed between 3 colors on click. How do we fix this? Do i need Python 3.x>

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
Ok, so i've got python 3.x and i'm ready for the next step...

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

>Yes, the canvas was blue at startup and changed between 3 colors on click. How do we fix this? 

You have to change in `class Knop` from `self.ss = Button(...` to `self.ss = Canvas(...`
But you can't use the same parameters, because a `Button` sizes on character size and a `Canvas` sizes on pixel size. See my example from the [first comment](https://github.com/TheOneDarkEye/Cube-Solver/issues/3#issue-490237979), there `width=100, height=100` defines the size to 100 pixel. 

Furthermore a `Canvas` does not hava a `command=` parameter. 
You have to use `canvas.bind(...` to get the **click**, it's doable, **i do some testing and come back**.

---

>Do i need Python 3.x>

No, as you see my above example works also with 2.7.

But changing to 3.x, then you are up to date and don't learn outdated things, it's a future step.
Also note, the support  for 2.7 has stoped.
The drawback, you have to update some more parts of the code too, to make it working with 3.x, so more work for you.

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

Read my new [Issue](https://github.com/TheOneDarkEye/Cube-Solver/issues/4) about the next step.
