### ISSUE TITLE
Decision: Stay with the given code or make a new clean version

### ISSUE THREAD

**Issue by WK-GiHu** [TheOneDarkEye/Cube-Solver#4]
@TheOneDarkEye 

Change from `Button` to `Canvas` 
You have to make a decision:

- [x] 1. Stay with the original source
    Esitmated time and effort:
   - Change all `class Knop`
    - Replace `Button` with `Canvas` 6 line
    - Replace `command=` with `.bind(..` 6 lines
    - Remove `.configure(..., activebackground=` 6 x 9 lines

- [ ] 2. Make a clean OOP version without [DRY vs WET solutions](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
   The number of code lines will be reduced from over 600 to 300!
   Esitmated time and effort:
     - Define a `class COLOR` and reuse it in the whole program.
     - Define a `class RepetitiveList` and reuse it in `class Knop` and `App`
     - Define a `class Knop` for **ALL** `Knop` in **ALL** `Face` only **ONCE**
     - Define a `class Face` for **ALL** faces only **ONCE**
     - Define a `class Arduino` to hold all Arduino related code in **one** `class`
     - Define a `class App` to put it all together

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
I think i'll go with option #1 to stay with original source...
