### ISSUE TITLE
Change from `Button` to `Canvas`

### ISSUE THREAD

**Issue by WK-GiHu** [TheOneDarkEye/Cube-Solver#5]
@TheOneDarkEye 
- [x] 1. Stay with the original source

 - Change in all `class Knop`, 6 times
   - [x] Add paramter `event` to the function paramter list of `human_move`:
   (*Line 182 , only for example*)
https://github.com/TheOneDarkEye/Cube-Solver/blob/6e9e35f9d05c48cdefed0707f805f9016b69629d/Send_Cube_State.py#L182
      Change to:  `def human_move(event):`

    - [x] Replace `Button` with `Canvas`
    - [x] Replace `command=` with `.bind(..`
https://github.com/TheOneDarkEye/Cube-Solver/blob/6e9e35f9d05c48cdefed0707f805f9016b69629d/Send_Cube_State.py#L184

      Change to: (*Line 184 and color 'yellow', only for example*)
      ```
            self.ss = Canvas(root, bg='yellow', width=100, height=100)
            self.ss.bind('<Button-1>', human_move)
       ```
    - [x] Remove `.configure(..., activebackground=` 6 x 9 lines
  Change in **all** function `change_color(...`, *Line 127, only for example*
https://github.com/TheOneDarkEye/Cube-Solver/blob/6e9e35f9d05c48cdefed0707f805f9016b69629d/Send_Cube_State.py#L127
**all** the lines, *Line 137 and color 'white', only for example*
https://github.com/TheOneDarkEye/Cube-Solver/blob/6e9e35f9d05c48cdefed0707f805f9016b69629d/Send_Cube_State.py#L137
to: `bb[x].ss.configure(bg='white')`

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
Do i change ALL of the "Button" with canvas? and what am i changing in the example for line 127? what you have posted is exactly what it says. Or is it saying change what is underneath this?

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
When running the code, 
"NameError: global name 'tk' is not defined"
and when i used capital "T"...
"AttributeError: class Tk has no attribute 'Canvas'"

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

>what am i changing in the example for line 127? what you have posted is exactly what it says. Or is it saying change what is underneath this?

Line 127 points to the function's where you find  `bb[x].ss.configure(`.
**Yes**, only **all** lines *underneath this*.

>"NameError: global name 'tk' is not defined"

Sorry, my bad, i have copied from my local version.
The `import`  line reads: `from Tkinter import *`.
The `*` imports **all** so no preceding `tk.` needed.

### Remove **all** `Tk.`

---

### One mistake

I assume you have used **Search and replace**, but the following 
https://github.com/TheOneDarkEye/Cube-Solver/blob/93f9248745c9726cf33d726800f0ca8947476910/Send_Cube_State.py#L187

should stay with `next_face = Button(...`, **no change here!**

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
I ran the newly edited code and this error appeared,

"Traceback (most recent call last):
  File "/Users/nelson.armstrong/Desktop/Send_Cube_State/Send_Cube_State 4.py", line 604, in <module>
    enter_cube()
  File "/Users/nelson.armstrong/Desktop/Send_Cube_State/Send_Cube_State 4.py", line 589, in enter_cube
    enter_yellow_face()
  File "/Users/nelson.armstrong/Desktop/Send_Cube_State/Send_Cube_State 4.py", line 169, in enter_yellow_face
    root = tk()
NameError: global name 'tk' is not defined"

Do i need to delete the lines reading, 
"root = tk()"
as well?

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

>line 169, in `enter_yellow_face` 
>`root = tk()`
>NameError: global name 'tk' is not defined"
>Do i need to delete the lines reading, `"root = tk()"` as well?

You have mixedup something, in the GitHub version of `Send_Cube_State.py` there is no Line 169 with `root = tk()`
They read correct:
https://github.com/TheOneDarkEye/Cube-Solver/blob/5313d27f4e5e1f6667e3d3c699c6b9b2df702bd6/Send_Cube_State.py#L172

---

Remove or comment `# ` these lines, as they no longer needed:
https://github.com/TheOneDarkEye/Cube-Solver/blob/5313d27f4e5e1f6667e3d3c699c6b9b2df702bd6/Send_Cube_State.py#L132
https://github.com/TheOneDarkEye/Cube-Solver/blob/5313d27f4e5e1f6667e3d3c699c6b9b2df702bd6/Send_Cube_State.py#L133
https://github.com/TheOneDarkEye/Cube-Solver/blob/5313d27f4e5e1f6667e3d3c699c6b9b2df702bd6/Send_Cube_State.py#L134

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
After running the code it worked to some extent...
![Screen Shot 2019-09-10 at 7 25 01 am](https://user-images.githubusercontent.com/40260331/64567702-2aec5100-d39c-11e9-8b1f-981a865c72ea.png)
the window doesn't show the boxes...

**Comment by WK-GiHu** [comment]
@TheOneDarkEye 

>After running the code it worked to some extent...

You have deleted the layout line [`self.ss.grid(row=self.row, column=self.col)`](https://github.com/TheOneDarkEye/Cube-Solver/commit/93f9248745c9726cf33d726800f0ca8947476910#r35014708), put it back.

**Comment by TheOneDarkEye** [comment]
@WK-GiHu 
OMG, IT WORKS!!!!!!!!!!!!!!!!!!
THANK YOU SO SO SO MUCH!!!!!!!!!!!
YOU ARE AMAZING!!!!!!!!!!!!!!!!!!!!!!!!
